AWSTemplateFormatVersion: '2010-09-09'
Description: Amazon S3 bucket to store Athena query results
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
Outputs:
  BucketName:
    Value: !Join ['', ['s3://', !Ref 'S3Bucket', '/athena/results/']] 
    Description: URI of the Amazon S3 bucket to store Athena query results